version: '3.8'

services:
  web:
    build: ./src
    volumes:
      - ./src/media:/usr/src/media/
    ports:
      - 8000:8000
    environment:
      - DB_URI=postgresql://cred:cred@db/memesdb
  db:
    image: postgres:15.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=cred
      - POSTGRES_PASSWORD=cred
      - POSTGRES_DB=memesdb

volumes:
  postgres_data: